---
- hosts: webserver # Nodes Group name or server hostname
  become: yes
  tasks: 
    - name: Install multiple packages
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

    - name: Start and  Enable Services
      service: name=apache2 state=started enabled=yes #state should be ( reloaded, restarted, started, stopped )
