---
- hosts: webserver
  become: yes
  tasks:
    - name: Install tool
      apt: name=python-mysqldb state=present update_cache=yes 
   
    - name: Install Mysql-server
      apt: name=mysql-server state=present update_cache=yes

    - name: change my.cnf file using lineinfile
      lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
                 line="bind-address = 0.0.0.0"
      notify: restart mysql-server

    - name: create demo databases
      mysql_db: name=demo state=present

    - name: create demo user
      mysql_user: name=demo password=Password@123 priv=demo.*:ALL host='%' state=present

  handleres:
    - name: restart mysql-server
      service: name=mysql-server state=restarted
