---
- hosts: webserver
  become: yes
  tasks:
    - name: Install Mysql-server
      apt: name=mysql-server state=present update_cache=yes

    - name: change my.cnf file using lineinfile
      lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
                 line="bind-address = 0.0.0.0"
      notify: restart mysql-server

  handleres:
    - name: restart mysql-server
      service: name=mysql-server state=restarted
